
name: Main Login Front - Deploy app to Azure

on:
  push:
    branches: [ "prod","uat" ]

env:
  APP_LOCATION: "/" # location of your client code
  APP_ARTIFACT_LOCATION: "dist" # location of client code build output

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: "${{github.ref_name}}"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo VITE_API_URL=$(az keyvault secret show --vault-name log${{github.ref_name}}-eastus2 --name VITE-API-URL --query value -o tsv) >> $GITHUB_ENV
          echo VITE_WEBSITE_URL=$(az keyvault secret show --vault-name log${{github.ref_name}}-eastus2 --name VITE-WEBSITE-URL --query value -o tsv) >> $GITHUB_ENV
          echo VITE_APP_TENANT_ID= >> $GITHUB_ENV

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
      env:
        VITE_API_URL: ${{ env.VITE_API_URL }}
        VITE_WEBSITE_URL: ${{ env.VITE_WEBSITE_URL }}
        VITE_APP_TENANT_ID: ${{ env.VITE_APP_TENANT_ID }}